apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-deploy
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app
    spec:
      containers:
        - name: {{ .Release.Name }}-nodejs
          image: '{{ .Values.werf.image.app }}'
          workingDir: /app
          env:
            - name: EKP_PLUGIN_ID
              value: 'splinterlands'
            - name: EKP_PLUGIN_NAME
              value: 'Splinterlands'
            - name: MONGO_HOST
              value: '{{ .Values.mongodb.host }}'
            - name: MONGO_DB_NAME
              value: '{{ .Release.Name }}'
            - name: REDIS_HOST
              value: '{{ .Release.Name }}-redis-master'
            - name: SENTRY_DSN
              value: '{{ .Values.sentry.dsn }}'
            - name: NODE_ENV
              value: '{{ .Values.werf.env | default "production" }}'
          ports:
            - containerPort: 3001
              protocol: TCP
